sudo: false
dist: trusty
language: java
jdk:
  - openjdk11

cache:
  directories:
    - "$HOME/.cache"

services:
  - docker

before_install:
  - cp ./.mvn/ci-settings.xml $HOME/.m2/settings.xml
  - wget --no-check-certificate https://archive.apache.org/dist/maven/maven-3/3.9.3/binaries/apache-maven-3.9.3-bin.tar.gz
  - tar xzvf apache-maven-3.9.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.9.3/bin:$PATH
  - mvn -v
  - docker --version
  #- docker pull ubuntu:18.04

jobs:
  include:
    - script: "mvn -P ci install -DskipTests"
    - stage: deploy
      provider: script
      script: "mvn -P ci deploy -DskipTests"
      on:
        tags: true
        branches: true
